import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Grihoker',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <nav className='center'>
          
          <ul>
            <img src="logo.png" alt=""></img>
            <li><a href='/'>Home</a></li>
            <li><a href='/Blog'>Blog</a></li>
            <li><a href='/Career'>Career</a></li>
            <li><a href='/Contact'>Contact Us</a></li>
            <select className="lang" id="lang">
             <option value="English">English</option>
              <option value="Bangla">Bangla</option>
            </select>
            
        </ul>
        </nav>
        <hr/>
        {children}
      <footer><h2>This is footer page</h2></footer>
      </body>
    </html>
  )
}
